### ISSUE TITLE
package.json 관련 issue

### ISSUE THREAD

**Issue by wnsgud0428** [Customizable-Planner/Customizable-Planner#1]
현재 npm, yarn 등을 통해 외부 패키지를 설치하면서 오류가 많이 생기는 것 같음.
package.json, package-lock.json 등과 같은 파일들의 관리가 필요한듯...

**Comment by quadbeats** [comment]
package 건드리는 거는 팀원 다 같이 토론이 필요할듯합니다.

**Comment by Kchanghun** [comment]
npm 에 외부 package를 install 한 뒤에
terminal창에 yarn입력하면 package.json등의 파일들이 setting됩니다.
